on:
  issues:
    types: [opened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A test
    steps:
    - name: Counting words
      id: count
      uses: ryanbraganza/word-count-action@v6
      with:
        words: 'Some words are here.'
    # Use the output from the `hello` step
    - name: Output
      run: echo "The count was ${{ steps.count.outputs.count }}"
